### POST
POST http://localhost:4000/api/patients
Content-Type: application/json

{
  "name": "Mehbooba Muftilal",
  "email": "mehbooba@email.com",
  "address": "222 Mufti chali",
  "dateOfBirth": "1955-03-22",
  "registeredDate": "2020-05-01"
}