### POST
POST http://localhost:4000/api/patients
Content-Type: application/json

{
  "name": "Anjali Kafki",
  "email": "anjali1@email.com",
  "address": "1234 kafki street",
  "dateOfBirth": "1996-03-25",
  "registeredDate": "2022-06-17"
}